# Generated by Django 5.0.4 on 2024-05-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comments_user_lesson_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
