# Generated by Django 5.0.4 on 2024-04-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date Posted')),
                ('content', models.CharField(max_length=255, verbose_name='Comment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lesson')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
