# Generated by Django 5.0.4 on 2024-04-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_app.lesson'),
        ),
    ]
